name: mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^10.0.0
  stripe_platform_interface: ^10.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.4.7
  flutter_ai_toolkit: ^0.8.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.4.0
  fl_chart: ^0.68.0 # Or latest version of the intended fl_chart
  awesome_snackbar_content: ^0.1.6
  redacted: ^1.0.13
  google_fonts: ^6.2.1
  toastification: ^3.0.2
  material_floating_search_bar_2: ^0.5.0
  video_player_media_kit: ^1.0.6
  media_kit: ^1.2.0
  cupertino_sidebar: ^1.0.1
  drop_down_search_field: ^1.1.3
  skeletonizer: ^1.4.3
  gal: ^2.3.1
  wolt_modal_sheet: ^0.11.0
  introduction_screen: ^3.1.17
  flutter_native_splash: ^2.4.6
  platformx: ^1.1.0
  graphql: ^5.1.2
  fluro: ^2.0.5
  animated_toggle_switch: ^0.8.5
  animated_text_kit: ^4.2.3
  meta: ^1.16.0
  linkpeek: ^1.0.0
  web_socket_channel: ^3.0.3
  graphql_flutter: ^5.1.2
  flutter_secure_storage: ^9.0.0
  flutter_login: ^4.0.0
  google_sign_in: ^6.3.0
  nearby_service: ^0.2.0
  auto_translator: ^2.3.5
  tab_container: ^3.5.3
  shared_preferences: ^2.2.2
  intl_utils: ^2.8.10
  dio: ^5.4.0
  intl: ^0.20.2 # Align with flutter_localizations
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  flutter_animate: ^4.5.2
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  flutter_sound: ^9.6.1 # Or latest version
  logging: ^1.3.0
  lucide_icons: ^0.257.0
  animate_do: ^3.3.9
  flutter_query: ^0.2.0
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.7
  share_plus: ^11.0.0
  responsive_framework: ^1.5.1
  flutter_zoom_drawer: ^3.2.0
  hidden_drawer_menu: ^3.0.1
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  flutter_slidable: ^4.0.0
  badges: ^3.1.2
  flutter_form_builder: ^10.0.1
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Enable native assets
experiments:
  native-assets: true
