import type { Property, User } from "@prisma/client";
import { z } from "zod";

// Custom Zod type for User and Property
const userCustom = z.custom<User>((data): data is User => {
  return typeof data === "object" && data !== null && "id" in data;
}, "Invalid User type");

const propertyCustom = z.custom<Property>((data): data is Property => {
  return typeof data === "object" && data !== null && "id" in data;
}, "Invalid Property type");

// Favorite Schema
export const FavoriteSchema = z.object({
  id: z.string().uuid(), // Using uuid since it's generated by cuid()
  userId: z.string().uuid(),
  propertyId: z.string().uuid(),

  // Timestamps
  createdAt: z.date(),
  updatedAt: z.date(),
  deletedAt: z.date().nullable().optional(),

  // Relations
  user: userCustom.optional(),
  property: propertyCustom.optional(),
});

// Create Favorite Schema
export const CreateFavoriteSchema = z.object({
  propertyId: z.string().uuid(),
  userId: z.string().uuid(),
});

// Update Favorite Schema
export const UpdateFavoriteSchema = z.object({
  id: z.string().uuid(),
  deletedAt: z.date().optional(),
});

// Toggle Favorite Schema
export const ToggleFavoriteSchema = z.object({
  userId: z.string().uuid(),
  propertyId: z.string().uuid(),
});

// Favorite Filter Schema
export const FavoriteFilterSchema = z.object({
  userId: z.string().uuid().optional(),
  propertyId: z.string().uuid().optional(),
  createdAtFrom: z.date().optional(),
  createdAtTo: z.date().optional(),
  updatedAtFrom: z.date().optional(),
  updatedAtTo: z.date().optional(),
  deletedAtFrom: z.date().optional(),
  deletedAtTo: z.date().optional(),
  sortBy: z.enum(["createdAt", "updatedAt", "deletedAt"]).optional(),
  sortOrder: z.enum(["asc", "desc"]).optional(),
  page: z.number().min(1).optional(),
  pageSize: z.number().min(1).max(100).optional(),
});

// Zod Type Inference for TypeScript
export type Favorite = z.infer<typeof FavoriteSchema>;
export type CreateFavoriteInput = z.infer<typeof CreateFavoriteSchema>;
export type UpdateFavoriteInput = z.infer<typeof UpdateFavoriteSchema>;
export type ToggleFavoriteInput = z.infer<typeof ToggleFavoriteSchema>;
export type FavoriteFilterInput = z.infer<typeof FavoriteFilterSchema>;
